### ISSUE TITLE
Específica el lenguaje de las porciones de código

### ISSUE THREAD

**Issue by cgosorio** [gonmurillo/TFG_EDVR#3]
En el último cuaderno has puesto varias porciones de código literal en el markdown. Cuando haces esto, existe sintaxis resaltada para muchos lenguajes que puedes obtener sin más que especificar el lenguaje que estás utilizando.

Sería la diferencia entre:
```
name: EDVR_L_x4_REDS_SRblur_official
model_type: EDVRModel
scale: 4
num_gpu: 4 
manual_seed: 0
```
y esto otro
```yaml
name: EDVR_L_x4_REDS_SRblur_official
model_type: EDVRModel
scale: 4
num_gpu: 4 
manual_seed: 0
```

Lo único que he hecho es poner «yaml» después de los tres backticks iniciales.
